// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  auth: dynamic(() => import("./Auth")),
  bento: dynamic(() => import("./Bento")),
  call_to_action: dynamic(() => import("./CallToAction")),
  case_studies: dynamic(() => import("./CaseStudies")),
  hero: dynamic(() => import("./Hero")),
  integrations: dynamic(() => import("./Integrations")),
  rich_text: dynamic(() => import("./RichText")),
  show_case: dynamic(() => import("./ShowCase")),
};
